name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_script: build:win
            artifact_name: rtmp-srt-server-win.exe
          - os: macos-latest
            build_script: build:mac
            artifact_name: rtmp-srt-server-macos
          - os: ubuntu-latest
            build_script: build:linux
            artifact_name: rtmp-srt-server-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build executable
        run: |
          npm run clean
          npm run ${{ matrix.build_script }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/rtmp-srt-server-win.exe/rtmp-srt-server-win.exe
            artifacts/rtmp-srt-server-macos/rtmp-srt-server-macos
            artifacts/rtmp-srt-server-linux/rtmp-srt-server-linux
          body: |
            ## What's Changed
            * Automatic release from GitHub Actions
            * Windows, macOS, and Linux executables included
            * NPM package published
          draft: false
          prerelease: false
      
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@devozdemirhasancan'
      
      - name: Configure NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 